services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: DATABASE_URL
        fromDatabase:
          name: bookly-db
          property: connectionString

  - type: web
    name: react-frontend
    env: static
    buildCommand: cd client/bookstore && npm install && npm run build
    staticPublishPath: client/bookstore/dist